package components

func Registry() []Component {
	return []Component{
		{
			ID:                 "engram",
			Name:               "Engram",
			Description:        "Persistent memory backend for SDD artifacts and session knowledge.",
			Category:           "artifact_store",
			Status:             StatusAvailable,
			Required:           true,
			Optional:           false,
			InstallSupported:   false,
			ConfigureSupported: true,
			Notes:              "Runtime detection is implemented; use `components engram status|configure`.",
		},
		{
			ID:                 "context7",
			Name:               "Context7",
			Description:        "Documentation lookup integration for up-to-date library guidance.",
			Category:           "integration",
			Status:             StatusAvailable,
			Required:           false,
			Optional:           true,
			InstallSupported:   false,
			ConfigureSupported: true,
			DocsURL:            "https://context7.com",
			Notes:              "Runtime detection/config metadata supported via `components context7 status|configure`.",
		},
		{
			ID:                 "mcps",
			Name:               "MCPs",
			Description:        "Model Context Protocol integrations used by automation workflows.",
			Category:           "integration",
			Status:             StatusAvailable,
			Required:           false,
			Optional:           true,
			InstallSupported:   false,
			ConfigureSupported: true,
			Notes:              "Initial MCP metadata registry is available via `components mcps status|list`.",
		},
		{
			ID:                 "skills",
			Name:               "Skills",
			Description:        "Internal skills metadata registry and config visibility for agent-targeted capabilities.",
			Category:           "platform",
			Status:             StatusAvailable,
			Required:           true,
			Optional:           false,
			InstallSupported:   false,
			ConfigureSupported: true,
			Notes:              "Metadata-only commands available via `components skills status|list|configure`.",
		},
		{
			ID:                 "sdd",
			Name:               "SDD",
			Description:        "Spec-Driven Development workflow and artifact lifecycle.",
			Category:           "workflow",
			Status:             StatusAvailable,
			Required:           true,
			Optional:           false,
			InstallSupported:   false,
			ConfigureSupported: false,
			Notes:              "Modeled as available workflow; runtime detection/execution checks are not implemented yet.",
		},
		{
			ID:                 "sdr",
			Name:               "SDR",
			Description:        "Structured development review workflow for release readiness.",
			Category:           "workflow",
			Status:             StatusNotImplemented,
			Required:           false,
			Optional:           true,
			InstallSupported:   false,
			ConfigureSupported: false,
			Notes:              "Reserved for later phase; command hooks are intentionally absent.",
		},
		{
			ID:                 "redteam",
			Name:               "Red Team",
			Description:        "Adversarial review workflow for hardening automation behavior.",
			Category:           "workflow",
			Status:             StatusNotImplemented,
			Required:           false,
			Optional:           true,
			InstallSupported:   false,
			ConfigureSupported: false,
			Notes:              "No local runner is implemented in this batch.",
		},
	}
}
